# Generated by Django 2.2.16 on 2022-03-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220319_1248'),
        ('reviews', '0003_user_confirmation_code'),
    ]

    operations = [
    ]
